name: Submission of abstract for Birds-of-a-feather session
description: File a abstract submission
title: "[bof]: REPLACE ME WITH YOUR BOF ABSTRACT TITLE"
labels: [bof, abstract]
assignees:
  - kozo2
body:
  - type: markdown
    attributes:
      value: |
        Please submit this form and let us know your BOF abstract. Reviews will be done openly on the issue created by the submission.
        Please review the BioC Asia 2021 Code of Conduct before submitting this form. Thanks for taking the time to fill out this form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you (if we need to exchange information privately)?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: bof-abstract
    attributes:
      label: Abstract
      description: Write an abstract of your BOF.
      placeholder: Tell us your talk abstract!
      value: "It is about Bioconductor related R package or community. It is ..."
    validations:
      required: true
  - type: textarea
    id: date-preference
    attributes:
      label: A convenient da for your BOF.
      description: However, the request is not always reflected.
  - type: textarea
    id: comment
    attributes:
      label: Comment field
      description: Please let us know if there is anything else.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the following before submitting.
      options:
        - label: This event has a Bioconductor focus or interest to Bioconductor users/developers.
          required: true
        - label: I checked and confirmed the [BioC Asia 2021 Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
          required: true
