name: Submission of abstract for Long workshop session
description: File a abstract submission
title: "[workshop]: REPLACE ME WITH YOUR LONG WORKSHOP ABSTRACT TITLE"
labels: [workshop]
assignees:
  - kozo2
body:
  - type: markdown
    attributes:
      value: |
        Please submit this form and let us know your Long workshop abstract. Reviews will be done openly on the issue created by the submission.
        Workshops can be conducted in Japanese, Mandarin, or English.
        However, please write the abstract in English so that anyone can understand the content of this review.
        Please review [the BioC Asia 2021 Code of Conduct](https://biocasia2021.bioconductor.org/code/) before submitting this form.
        We ask that your workshop be conducted using our [Orchestra platform](http://app.orchestra.cancerdatasci.org/) whenever possible.
        Create workshops from [this template project](https://github.com/seandavi/BuildABiocWorkshop) whenever possible.
        Following this will make your workshop reproducible without having to set up the local environment.
        Thanks for taking the time to fill out this form!
  - type: textarea
    id: workshop-abstract
    attributes:
      label: Abstract
      description: Write an abstract of your Long workshop.
      placeholder: Tell us your workshop abstract!
      value: "REPLACE ME WITH YOUR LONG TALK ABSTRACT"
    validations:
      required: true
  - type: dropdown
    id: language
    attributes:
      label: Language used in the workshop
      description: Which language do you use in your workshop?
      options:
        - Japanese
        - Mandarin
        - English
    validations:
      required: true
  - type: textarea
    id: date-preference
    attributes:
      label: Convenient day for your Long workshop.
      description: However, the request is not always reflected.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: It is optional to write here. If you do not want your email address to be published, you do not have to write it. We will use the email address if we need to contact you privately.
      placeholder: ex. email@example.com
  - type: textarea
    id: comment
    attributes:
      label: Comment field
      description: Please let us know if there is anything else.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the following before submitting.
      options:
        - label: This workshop has a Bioconductor focus or interest to Bioconductor users/developers.
          required: true
        - label: I checked and confirmed the [BioC Asia 2021 Code of Conduct](https://biocasia2021.bioconductor.org/code/).
          required: true
        - label: I understood that it would be desirable for the workshop to be based on [this template project](https://github.com/seandavi/BuildABiocWorkshop).
          required: true
